<a href="https://colab.research.google.com/github/wearended/tutorial-3/blob/main/Tutorial%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
b = np.random.rand(3,4)
print(b)

[[0.97797007 0.20209396 0.19407323 0.56308874]
 [0.94734577 0.94586428 0.26231052 0.51800766]
 [0.1346159  0.07711855 0.4934968  0.88369852]]


In [4]:
c = np.full(5, 1)
d = np.full(5, 0)
print(c)
print(d)

[1 1 1 1 1]
[0 0 0 0 0]


In [5]:
e = np.random.rand(6,3)
e.transpose()

array([[0.76211853, 0.395399  , 0.14745389, 0.02203684, 0.05431801,
        0.43755116],
       [0.45059   , 0.75574423, 0.5143559 , 0.12164459, 0.76599373,
        0.0370476 ],
       [0.52126901, 0.93418052, 0.6087645 , 0.57856066, 0.05585852,
        0.6239948 ]])

In [6]:
n = 2
p = 3
m = 4
f = np.random.rand(n,p)
g = np.random.rand(p,m)
print(f @ g)

[[0.5519055  0.49299158 0.36875466 0.10866506]
 [0.83576358 0.66947764 0.54914706 0.2247156 ]]


In [7]:
print(np.dot(f, g))

[[0.5519055  0.49299158 0.36875466 0.10866506]
 [0.83576358 0.66947764 0.54914706 0.2247156 ]]
